# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# See http://symfony.com/fr/doc/current/components/yaml/yaml_format.html
# See http://codebeautify.org/yaml-validator

# APPLICATION SETTINGS

# Jersey
spring.jersey.type: servlet

# LOGGING
logging.path: /var/log/tomcat
logging.file: spring-boot-ws.log
#logging.config: ./src/main/resources/log4j2.xml
