# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# See http://symfony.com/fr/doc/current/components/yaml/yaml_format.html
# See http://codebeautify.org/yaml-validator

# APPLICATION SETTINGS
spring:
    main.show-banner: false
    main.web-environment: true

# Jersey
spring.jersey.type: servlet

# LOGGING
logging.path: /var/log/tomcat
logging.file: spring-boot-ws.log
logging.config: /etc/conf/spring-boot-ws/log4j2.xml
